// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUpQaCGRo1STutN1yo6Mkcm3bjdoAzEMI',
    appId: '1:197996581430:web:86160ac1aa1bb9f55a7e97',
    messagingSenderId: '197996581430',
    projectId: 'th4-economic-app',
    authDomain: 'th4-economic-app.firebaseapp.com',
    storageBucket: 'th4-economic-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DOEO_QZPnOYjFPyZPB-Oj2LuvJhupsc',
    appId: '1:197996581430:android:0228cf7dd77aacf75a7e97',
    messagingSenderId: '197996581430',
    projectId: 'th4-economic-app',
    storageBucket: 'th4-economic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtQyPapxgCKDQtuOWHEXk57RBpcpsta10',
    appId: '1:197996581430:ios:c838ff61ec36f5495a7e97',
    messagingSenderId: '197996581430',
    projectId: 'th4-economic-app',
    storageBucket: 'th4-economic-app.firebasestorage.app',
    androidClientId: '197996581430-29jh668mqkd9qdn5n1fh5e48442eceqr.apps.googleusercontent.com',
    iosClientId: '197996581430-3gei9efmnidtav6iuqfq5rg8ojqqru0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.th4economicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtQyPapxgCKDQtuOWHEXk57RBpcpsta10',
    appId: '1:197996581430:ios:c838ff61ec36f5495a7e97',
    messagingSenderId: '197996581430',
    projectId: 'th4-economic-app',
    storageBucket: 'th4-economic-app.firebasestorage.app',
    androidClientId: '197996581430-29jh668mqkd9qdn5n1fh5e48442eceqr.apps.googleusercontent.com',
    iosClientId: '197996581430-3gei9efmnidtav6iuqfq5rg8ojqqru0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.th4economicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUpQaCGRo1STutN1yo6Mkcm3bjdoAzEMI',
    appId: '1:197996581430:web:c8a843e52ea210ec5a7e97',
    messagingSenderId: '197996581430',
    projectId: 'th4-economic-app',
    authDomain: 'th4-economic-app.firebaseapp.com',
    storageBucket: 'th4-economic-app.firebasestorage.app',
  );
}
